---
title: "Visualizzazione decessi settimanali nei comuni italiani"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(Encoding="UTF-8")
```

```{r include=FALSE}
library(tidyverse)
library(lubridate)
library(tibbletime)

library(RColorBrewer)
theme_set(theme_bw())

# Importa dataset analitico decessi giornalieri
# fonte: https://www.istat.it/it/archivio/240401 

# Imposta lingua data/ora (utile se il sistema è in altre lingue)
Sys.setlocale("LC_TIME", "Italian") 

decessi_comuni <- read_csv("./dati_anpr/comune_giorno.csv", locale = locale(encoding = "Windows-1252")) %>% 
  # codifica classi di classe_eta
  mutate(classe_eta = factor(
    CL_ETA,
    levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21"),
    labels = c("0", "1-4", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80-84", "85-89", "90-94", "95-99", "100+")
  ),
  # codifica data decesso GE è nel formato MMGG 
  giorno_decesso = paste0(GE, "2020") %>% mdy()
  ) %>% 
  select(
    regione = NOME_REGIONE,
    comune = NOME_COMUNE, 
    classe_eta, giorno_decesso, everything()
  ) %>% 
  # ristruttura dati in formato lungo per facilitare il confronto con anni precedenti
  pivot_longer(cols = MASCHI_15:TOTALE_20, names_to = "classe", values_to = "decessi") %>%
  # scorpora variabile decesso per genere in anni precedenti 
  separate(classe, into = c("sesso", "anno"), sep = "_") %>% 
  mutate(
    anno = paste0("20", anno),
    decessi = na_if(decessi, 9999), # 9999 è usato per indicare valori mancanti in date future
    sesso = factor(sesso) 
  ) %>% 
select(regione, comune, classe_eta, giorno_decesso, GE, sesso, anno, decessi) 
```


# Visualizza totale decessi settimanali 2020, rispetto ad anni precedenti, per comune selezionato
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
decessi_comuni %>% 
  # dichiara indice tempo tabella, per calcoli totali settimanali
  as_tbl_time(index = giorno_decesso) %>% 
  filter(comune == "Bergamo") %>%
  # esclude non ancora pervenute
  filter(giorno_decesso < dmy("28/03/2020")) %>% 
  # Raggruppa classi di classe_eta
  mutate(
    classe_eta = fct_collapse(
      classe_eta,
      `0-34` = c("0", "1-4", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34"),
      `35-54` = c("35-39", "40-44", "45-49", "50-54"),
      `55-74` = c("55-59", "60-64", "65-69", "70-74"),
      `75+`   = c("75-79", "80-84", "85-89", "90-94", "95-99", "100+")
    )
  ) %>% 
  # calcola decessi settimanali 
  collapse_by("weekly") %>%
  group_by(giorno_decesso, classe_eta, anno, sesso) %>% 
  summarise(decessi = sum(decessi)) %>% 
  ggplot(aes(x = giorno_decesso, y = decessi, color = anno)) +
  geom_point() + geom_line() +
  scale_color_brewer(palette = "YlOrBr") +
  scale_x_date(date_labels = "%V: %e %b") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  facet_grid(classe_eta ~ sesso) +
  labs(
    title = "Totale decessi settimanali nel comune di Bergamo, per sesso e classi di età",
    subtitle = "Confronto tra prime settimane 2020 con corrispondenti 2015-2019",
    y = "Totale decessi"
  )
```
  


