---
title: "Visualizzazione dati COVID-19 in Italia"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=F, warning=FALSE, include=FALSE}
library(tidyverse)
library(lubridate)
library(directlabels)
library(ggthemes)
library(RColorBrewer)
library(scales)
library(tibbletime)

# Tema ggplot minimalista
theme_set(theme_minimal())

# Imposta lingua data/ora (utile se il sistema è in altre lingue)
Sys.setlocale("LC_TIME", "Italian") 

# Ripartizioni geografiche ----
# Ripartizione a 5: Nord-ovest, Nord-est, Centro, Sud, Isole (definizione Istat)
# Ripartizione a 3: Nord, Centro, Sud
rip_regioni <- read_csv("ripartizione_regioni.csv", col_types = "ccc") %>% 
  mutate(
    ripartizione_3 = factor(ripartizione_3) %>% fct_inorder(),
    ripartizione_5 = factor(ripartizione_5) %>% fct_inorder()
  )

# Scaricare tabella riepilogativa dati regionali ----
dati_regionali <- read_csv(
  # Percorso tabella riepilogativa, aggiornata giornalmente
  file = "https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv",
  # Schema tabella: specifica tipo di dato colonne;
  # (La specifica non è strettamente necessaria, ma rende l'importazione della tabella più robusta a errori)
  col_types = cols(
    .default = col_double(),
    data = col_datetime(),
    stato = col_character(),
    codice_regione = col_character(),
    denominazione_regione = col_character(),
    note_it = col_character(),
    note_en = col_character()
  )
) %>%
  rename("regione" = "denominazione_regione") %>%
  # Aggungere ripartizioni delle regioni
  left_join(rip_regioni, by = "regione") %>% 
  # Data come giorno, rimuovendo ora del giorno
  mutate(data = as.Date(data))

# Calcolo incremento giornalieri
dati_regionali <- dati_regionali %>%
  group_by(regione) %>%
  mutate(
    nuovi_deceduti = deceduti - lag(deceduti, 1),
    nuovi_ospedalizzati = totale_ospedalizzati - lag(totale_ospedalizzati, 1),
    nuovi_terapia_int = terapia_intensiva - lag(terapia_intensiva, 1),
    nuovi_tamponi = tamponi - lag(tamponi, 1),
    nuovi_positivi = totale_casi - lag(totale_casi, 1)
  ) %>%
  ungroup()


# Elenco ordinato di regioni da includere nel grafico
regioni_scelte <- c("Lombardia", "Veneto", "Piemonte", "Emilia-Romagna", "Toscana", "Lazio")
```


# Progressione relativa
```{r}
# Elenco ordinato di regioni da includere nel grafico
regioni_scelte <- c("Lombardia", "Veneto", "Piemonte", "Emilia-Romagna", "Toscana")

dati_regionali %>%
  mutate(regione_evidenziata  = if_else(regione %in% regioni_scelte, regione, NA_character_)) %>% 
  group_by(regione) %>% 
  filter(totale_casi >= 10) %>% 
  mutate(giorno_epidemia = 1:n()) %>% 
  ggplot(aes(x = giorno_epidemia, y = totale_casi, group= regione, color = regione_evidenziata)) +
  geom_point(data = . %>% filter(!is.na(regione_evidenziata)), size = 1) +
  geom_line() +
  scale_y_log10() + annotation_logticks(sides = "l") +
  labs(
    title = "Progressione casi totali COVID-19", subtitle = "Per Regione o Provincia Autonoma",
    x = "Giorni trascorsi dopo il decimo caso", y = "Casi totali (scala logaritmica)"
  )
```


# Grafici andamento regionale nel tempo
```{r echo=FALSE, message=FALSE, warning=FALSE}
dati_regionali %>%
  ggplot(aes(x = data, y = totale_casi, color = ripartizione_5)) +
  geom_point() +
  geom_line() +
  scale_y_log10() + annotation_logticks(sides = "l") +
  facet_wrap(~ regione, ncol = 5) +
  labs(
    title = "Totale cumulato casi COVID-19", subtitle = "Per Regione o Provincia Autonoma",
    x = NULL, y = "Casi totali (scala logaritmica)"
  )
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
dati_regionali %>%
  group_by(regione) %>%
  arrange(regione, data) %>%
  mutate(diff_decessi = c(NA, diff(deceduti))) %>%
  ggplot(aes(x = data, y = diff_decessi)) +
  geom_col() +
  scale_y_log10() + 
  annotation_logticks(sides = "l") +
  facet_wrap(~regione, ncol = 5) +
  labs(
    title = "Differenza giornaliere decessi COVID-19", subtitle = "Per Regione o Provincia Autonoma",
    x = NULL, y = "Differenza decessi (scala logaritmica)"
  )
```

# Incrementi Giornalieri per Regione 
```{r echo=FALSE, message=FALSE, warning=FALSE}
dati_regionali %>% 
  # Selezione regioni, e ordina livelli fattore (e quindi posizione grafico) secondo elenco
  filter(regione %in% regioni_scelte) %>% 
  mutate(regione = fct_relevel(regione, regioni_scelte)) %>%
  # ristruttura dati per distinguere le variabili nuovi_positivi, nuovi_terapia_int, nuovi_deceduti
  select(data, regione, nuovi_positivi, nuovi_terapia_int, nuovi_deceduti) %>% 
  pivot_longer(cols = nuovi_positivi:nuovi_deceduti) %>% 
  # Riordina e rinomina variabili per il grafico (etichette livelli categorica)
  mutate(name = factor(name, 
    levels = c("nuovi_positivi", "nuovi_terapia_int", "nuovi_deceduti"), # nomi osservati nei dati, riordinati
    labels = c("positivi", "terapia intensiva", "deceduti") # nuovi nomi variabili, in ordine cui sopra
    )) %>% 
  ggplot(aes(x = data, y = value, fill = name)) + 
  geom_col(position = "dodge") + 
  facet_grid(name ~ regione, scales = "free_y") + 
  scale_x_date(date_labels = "%d %b") +
  scale_y_continuous(labels = scales::comma) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(legend.position = "none") +
  labs(
    title = "Positivi, Terapie Intensive, Deceduti",
    x = NULL, y = NULL,
    subtitle = "Incremento giornaliero"
    )
```


# Curve di casi Totale per Regione 
```{r echo=FALSE, message=FALSE, warning=FALSE}
dati_regionali %>% 
  # Selezione regioni, e ordina livelli fattore (e quindi posizione grafico) secondo elenco
  filter(regione %in% regioni_scelte) %>% 
  mutate(regione = fct_relevel(regione, regioni_scelte)) %>%
  # ristruttura dati per distinguere le variabili positivi, terapia_int, deceduti
  select(data, regione, totale_positivi, terapia_intensiva, deceduti) %>% 
  pivot_longer(cols = totale_positivi:deceduti) %>% 
  # Riordina e rinomina variabili per il grafico (etichette livelli categorica)
  mutate(name = factor(name, 
    levels = c("totale_positivi", "terapia_intensiva", "deceduti"), # nomi osservati nei dati, riordinati
    labels = c("positivi", "terapia intensiva", "deceduti") # nuovi nomi variabili, in ordine cui sopra
    )) %>% 
  ggplot(aes(x = data, y = value, fill = name)) + 
  geom_col() + 
  facet_grid(name ~ regione, scales = "free_y") + 
  scale_x_date(date_labels = "%d %b") + 
  scale_y_continuous(labels = scales::comma) + 
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title = "Positivi, Terapie Intensive, Deceduti",
    x = NULL, y = NULL,
    subtitle = "Totali per Regione"
  )
```



# Ripartizioni geografiche

```{r echo=FALSE, message=FALSE, warning=FALSE}
nr_regioni_colpite <- 4 ## Seleziona numero di regioni colpite


# Seleziona regioni più colpite
dati_regioni_colpite <- dati_regionali %>%
  # nella data più recente
  filter(data == max(data)) %>%
  # raggruppa regioni per ogni ripartizione
  group_by(ripartizione_3) %>%
  # seleziona N regioni più colpite sulla base di totale_casi
  top_n(n = nr_regioni_colpite, wt = totale_casi) %>% 
  # assegna numeri progressivi alle regioni, 
  # ripetuti tra ripartizioni diverse, per colori e forme
  ungroup %>% arrange(ripartizione_3, desc(totale_casi)) %>% 
  mutate(reg_colpita = 1:n() %>% factor()) %>% 
  # Seleziona i dati per solo queste regioni
  select(regione, reg_colpita) %>% 
  left_join(dati_regionali, by = "regione") 


ggplot(dati_regioni_colpite, aes(x = data, y = totale_casi, group = regione, label = regione, color = reg_colpita, shape = reg_colpita)) +
  geom_line(size = 0.6) +
  geom_point() +
  facet_grid(~ ripartizione_3) +
  geom_dl(method = "smart.grid", cex = 0.8) +
  scale_y_log10() + annotation_logticks(sides = "l") +
  scale_x_date(breaks = "1 week", date_labels = "%d %b") +
  scale_color_manual(values = brewer.pal(n = nr_regioni_colpite, 'Set2') %>% rep(3)) +
  scale_shape_manual(values = c(0, 1, 2, 4) %>% rep(3)) +
  theme(
    legend.position = "none", 
    axis.text.x = element_text(angle = 45, hjust = 1)
    ) + 
  labs(
    title = "Curva Epidemica Per Regioni in Aree Geografiche", subtitle = "Scala logaritmica",
    x = NULL, y = "Totale Casi"
  )
```



# Tasso tamponi positivi

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Definisce funzione per calcolo media mobile su due giorni
rolling_mean <- rollify(mean, window = 2)

dati_regionali %>% 
  group_by(regione) %>% 
  filter(regione %in% c("Lombardia", "Veneto", "Emilia-Romagna", "Toscana", "Lazio", "Piemonte", "Campania")) %>% 
  mutate(tasso_positivi = rolling_mean(totale_positivi / tamponi)) %>%
  ggplot(aes(x = data, y = tasso_positivi, color = regione, label = regione)) + 
  geom_dl(method = "last.qp") +
  geom_point() + geom_line() + 
  theme(
    legend.position = "none", 
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) + 
  scale_x_date(breaks = "1 week", date_labels = "%d %b", limits = c(ymd(2020-02-28), max(dati_regionali$data) + days(3))) +
  scale_y_continuous(labels = scales::percent) + 
  labs(
    title = "Tasso di test tampone positivi",
    y = "Tamponi positivi su tamponi effettuati", x = NULL,
    subtitle = "Media mobile di 2 giorni"
  )
```


# Nuovi tamponi e nuovi positivi

```{r echo=FALSE, message=FALSE, warning=FALSE}

dati_regionali %>% 
  # Selezione regioni, e ordina livelli fattore (e quindi posizione grafico) secondo elenco
  filter(regione %in% regioni_scelte) %>% 
  mutate(regione = fct_relevel(regione, regioni_scelte)) %>%
  # ristruttura dati per includere le variabili nuovi_tamponi e nuovi_positivi
  select(data, regione, nuovi_tamponi, nuovi_positivi) %>% 
  pivot_longer(cols = nuovi_tamponi:nuovi_positivi) %>% 
  ggplot(aes(x = data, y = value, fill = name)) + 
  geom_col(position = "dodge") + 
  facet_wrap(~regione) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_x_date(breaks = "1 week", date_labels = "%d %b") +
  scale_y_continuous(labels = scales::comma) + 
  theme(legend.position = "top") +
  labs(
    title = "Tamponi effettuati e positivi",
    x = NULL, y = "Nuovi tamponi o positivi",
    subtitle = "Incremento giornaliero"
  )
```


# Ospedali e terapia intensiva 

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Elenco ordinato di regioni da includere nel grafico
regioni_scelte <- c("Lombardia", "Veneto", "Piemonte", "Emilia-Romagna", "Toscana", "Lazio")

dati_regionali %>% 
  # Selezione regioni, e ordina livelli fattore (e quindi posizione grafico) secondo elenco
  filter(regione %in% regioni_scelte) %>% 
  mutate(regione = fct_relevel(regione, regioni_scelte)) %>%
  # ristruttura dati per includere le variabili nuovi_tamponi e nuovi_positivi
  select(data, regione, totale_ospedalizzati, terapia_intensiva) %>% 
  pivot_longer(cols = totale_ospedalizzati:terapia_intensiva) %>% 
  ggplot(aes(x = data, y = value, fill = name)) + 
  geom_col(position = "dodge") + 
  facet_wrap(~ regione) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_x_date(breaks = "1 week", date_labels = "%d %b") +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_brewer(palette = "Dark2", direction = -1) + 
  theme(legend.position = "top") +
  labs(
    title = "Tamponi effettuati e positivi",
    subtitle = "Incremento giornaliero",
    x = NULL, y = "Nuovi tamponi o positivi"
  )
```  


# Stock e flow casi 

```{r echo=FALSE, message=FALSE, warning=FALSE}

# Elenco ordinato di regioni da includere nel grafico
regioni_scelte <- c("Lombardia", "Veneto", "Piemonte", "Emilia-Romagna", "Toscana", "Lazio")

dati_regionali %>% 
  # Selezione regioni, e ordina livelli fattore (e quindi posizione grafico) secondo elenco
  filter(regione %in% regioni_scelte) %>% 
  mutate(regione = fct_relevel(regione, regioni_scelte)) %>%
  select(data, regione, nuovi_positivi, totale_casi) %>%
  # Esclude casi nuovi_positivi < 0 (problema dati)
  mutate(nuovi_positivi = if_else(nuovi_positivi < 0, NA_real_, nuovi_positivi)) %>% 
  ggplot(aes(x = totale_casi, y = nuovi_positivi, color = regione)) + 
  geom_point() +
  geom_smooth() +
  facet_wrap(~ regione) + 
  scale_x_log10(labels = scales::comma_format(accuracy = 1.0)) +
  scale_y_log10(labels = scales::comma_format(accuracy = 1.0)) +
  coord_equal() + 
  scale_fill_brewer(palette = "Dark2", direction = -1) + 
  theme(legend.position = "none") +
  labs(
    title = paste0("Totale e incremento casi COVID-19 aggiornato al ", dati_regionali$data %>% max() %>% format("%d %B %Y")),
    subtitle = "Curva di tendenza LOESS; Esclude casi nuovi_positivi < 0 (problema dati)",
    x = "STOCK: Casi cumulati (scala logaritmica)", y = "FLOW: Nuovi casi (scala logaritmica)"
  )
```


# Distibuzione nuovi casi giornalieri (bunching?)

```{r echo=FALSE, message=FALSE, warning=FALSE}

# Elenco ordinato di regioni da includere nel grafico
regioni_scelte <- c("Lombardia", "Veneto", "Piemonte", "Emilia-Romagna", "Toscana", "Lazio")

dati_regionali %>% 
  # Selezione regioni, e ordina livelli fattore (e quindi posizione grafico) secondo elenco
  filter(regione %in% regioni_scelte) %>% 
  mutate(regione = fct_relevel(regione, regioni_scelte)) %>%
  select(data, regione, nuovi_positivi) %>%
  ggplot(aes(x = nuovi_positivi, fill = regione)) + 
  geom_dotplot() +
  # geom_density() +
  geom_rug() +
  facet_wrap(~ regione, scales = "free_x") + 
  scale_fill_brewer(palette = "Dark2", direction = -1) + 
  theme(legend.position = "none") +
  labs(
    title = "Distribuzione di nuovi casi giornalieri",
    subtitle = "per regione",
    x = "Numero di nuovi casi giornalieri", y = "Frequenza"
  )
```
